// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv-Le6-_IPNiUgv0YulZnBLpZ1fb8uSBQ',
    appId: '1:472384201308:web:da25b8aa851d8f82433c99',
    messagingSenderId: '472384201308',
    projectId: 'task-app-faa69',
    authDomain: 'task-app-faa69.firebaseapp.com',
    storageBucket: 'task-app-faa69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlca8B4Xf9XzlDe68qVAs0R4cjDffz3Y',
    appId: '1:472384201308:android:3a3924c270de1d1a433c99',
    messagingSenderId: '472384201308',
    projectId: 'task-app-faa69',
    storageBucket: 'task-app-faa69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwnF3ONA0deAfNR3llQONo97hHx-VTwak',
    appId: '1:472384201308:ios:5b6b3bd47d3253e8433c99',
    messagingSenderId: '472384201308',
    projectId: 'task-app-faa69',
    storageBucket: 'task-app-faa69.appspot.com',
    iosClientId: '472384201308-2572lg0u5uu4cdulr3r2shv10pnsccee.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionTache',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwnF3ONA0deAfNR3llQONo97hHx-VTwak',
    appId: '1:472384201308:ios:3640cc5b685c812c433c99',
    messagingSenderId: '472384201308',
    projectId: 'task-app-faa69',
    storageBucket: 'task-app-faa69.appspot.com',
    iosClientId: '472384201308-no6hg6g6j1cg8f5qavj735jd78j9pq4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionTache.RunnerTests',
  );
}
